.-=-----------------------[ Latest 10 uploads ]-----------------------=-.
| OWNER    GROUP     DIRECTORY                                     DATE |
|-=-------------------------------------------------------------------=-|
| red      STAFF     RedFTPdv1.0.BETA-RED                          0315 |
| red      STAFF     Another.test.v4.0.REGGED-RED                  0312 |
`-----------------------------------------------------------------------'
                 -[ Type SITE NEW to view this list ]-              
