.-=-----------------------------------------------------[SITE READD]--=-.
| USAGE: SITE READD <user>                                              |
|-=-------------------------------------------------------------------=-|
| Send this command to the server if you want to readd a deleted user.  |
| EXAMPLE: SITE READD red                                               |
| FLAGS  : 1, 2, 7                                                      |
`-----------------------------------------------------------------------'