.-=-----------------------------------------------------[SITE DELIP]--=-.
| USAGE: SITE DELIP <user> <ip_num>                                     |
|-=-------------------------------------------------------------------=-|
| Send this command to the server if you want to del a users ip.        |
| EXAMPLE: SITE DELIP red 1                                             |
| FLAGS  : 1, 2, 7                                                      |
`-----------------------------------------------------------------------'