.-=--------------------------------------------------[SITE GADDUSER]--=-.
| USAGE: SITE GADDUSER <group> <user> <pass> [ip1] [ip2]                |
|-=-------------------------------------------------------------------=-|
| Send this command to the server if you want to add an user to a group.|
| EXAMPLE: SITE GADDUSER Staff red red *@*                              |
| FLAGS  : 1, 7                                                         |
`-----------------------------------------------------------------------'