.-=----------------------------------------------------[SITE CHPASS]--=-.
| USAGE: SITE CHPASS <new_pass>                                         |
|-=-------------------------------------------------------------------=-|
| Send this command to the server if you want to change your own pass.  |
| EXAMPLE: SITE CHPASS red                                              |
| FLAGS  : *                                                            |
`-----------------------------------------------------------------------'