---+--------------------[ Last 10 Online users ]----------------------.
.##|  User   |  Group   | Tag Line             | Last Logon time      |
---+---------+----------+---------------------------------------------+
. 1 red       STAFF      0DC / Lz0              2001/02/27
. 2 red       STAFF      0DC / Lz0              2001/02/27
. 3 red       STAFF      0DC / Lz0              2001/02/27
. 4 red       STAFF      0DC / Lz0              2001/02/24
. 5 duckman   MiSHiMA    ooops. me ?            2001/02/21
. 6 red       STAFF      0DC / Lz0              2001/02/21
. 7 duckman   MiSHiMA    ooops. me ?            2001/02/21
. 8 red       STAFF      0DC / Lz0              2001/02/21
. 9 duckman   MiSHiMA    ooops. me ?            2001/02/20
.10 duckman   MiSHiMA    ooops. me ?            2001/02/20
---+--------+-----------+----------------------|----------------------|
