.-=---------------------------------------------------[SITE ADDUSER]--=-.
| USAGE: SITE ADDUSER <user> <pass> [ip1] [ip2]                         |
|-=-------------------------------------------------------------------=-|
| Send this command to the server if you want to add an user.           |
| EXAMPLE: SITE ADDUSER red red *@*                                     |
| FLAGS  : 1, 2, 7                                                      |
`-----------------------------------------------------------------------'