.-=--------------------------------------------------[SITE MOUNTDIR]--=-.
| USAGE: SITE MOUNTDIR <Name> <Directory>                               |
|-=-------------------------------------------------------------------=-|
| Send this command to the server if you want to mount a directory.     |
|                                                                       |
| NOTE   : Avoid long dir names - you should only do like the example.  |
| EXAMPLE: SITE MOUNTDIR Games c:\games                                 |
| FLAGS  : 1, 7                                                         |
`-----------------------------------------------------------------------'