.-=----------------------------------------------------[USER FIELDS]--=-.
| FIELD             VALUE(S)     DOES                                   |
|-=-------------------------------------------------------------------=-|
| RATIO             0-x          Change a user's ratio 0 = leech        |
| LOGINS            0-x          Change a user's logins 0 = unlimited   |
| FLAGS             ?            Change a user's flags (SITE FLAGS)     |
| PASS              ?            Change a user's password               |
|                                                                       |
| Example: SITE CHANGE red ratio 0                                      |
| Flags  : 1, 7                                                         |
`-=-------------------------------------------------------------------=-'