.-=-----------------------------------------------------[SITE CHGRP]--=-.
| USAGE: SITE CHGRP <user> <new_group>                                  |
|-=-------------------------------------------------------------------=-|
| Send this command to the server if you want to change a users group.  |
| EXAMPLE: SITE CHGRP red staff                                         |
| FLAGS  : 1, 7                                                         |
`-----------------------------------------------------------------------'
