.-=---------------------------------------------------[SITE DELUSER]--=-.
| USAGE: SITE DELUSER <user>                                            |
|-=-------------------------------------------------------------------=-|
| Send this command to the server if you want to del a user - flag 6    |
| EXAMPLE: SITE DELUSER red                                             |
| FLAGS  : 1, 2, 7                                                      |
`-----------------------------------------------------------------------'