.-=----------------------------------------------------[SITE UNDUPE]--=-.
| USAGE: SITE UNDUPE <filename>                                         |
|-=-------------------------------------------------------------------=-|
| Send this command to the server if you want to remove a file from dupe|
| EXAMPLE: SITE UNDUPE red.rar                                          |
| FLAGS  : C                                                            |
`-----------------------------------------------------------------------'