.-=---------------------------------------------------[SITE TAGLINE]--=-.
| USAGE: SITE TAGLINE <tagline>                                         |
|-=-------------------------------------------------------------------=-|
| Send this command to the server if you want to change your tagline.   |
| EXAMPLE: SITE TAGLINE I love RedFTPd                                  |
| FLAGS  : *                                                            |
`-----------------------------------------------------------------------'