.-=-------------------------------------------------[SITE DELSITEOP]--=-.
| USAGE: SITE DELSITEOP <user>                                          |
|-=-------------------------------------------------------------------=-|
| Send this command to the server if you want to remove a siteop.       |
| EXAMPLE: SITE DELSITEOP red                                           |
| FLAGS  : 1, 7                                                         |
`-----------------------------------------------------------------------'