.-=------------------------------------------------[SITE MOUNTCLEAR]--=-.
| USAGE: SITE MOUNTCLEAR <Name>                                         |
|-=-------------------------------------------------------------------=-|
| Send this command to the server if you want to remove a mounted dir.  |
|                                                                       |
| EXAMPLE: SITE MOUNTCLEAR Games                                        |
| FLAGS  : 1, 7                                                         |
`-----------------------------------------------------------------------'