.-=-------------------------------------------------------[SITE PRE]--=-.
| USAGE: SITE PRE <directory> <section>                                 |
|-=-------------------------------------------------------------------=-|
| Send this command to the server if you want to "pre" a release.       |
| EXAMPLE: SITE PRE redftpd.v1.0.beta-red 0day                          |
| FLAGS  : Everyone who have access to the pre-directories.             |
`-----------------------------------------------------------------------'