                        ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
ÚÄÄ+ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ³     SiTE RULES       ³ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ+ÄÄÄÄÄÄ¿
³  ³                    ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ               ³      ³
³##³ Rule                                                      ³ Nuke ³
+ÄÄ+ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ+ÄÄÄÄÄÄÙ
³  ³ GENERAL RULES                                             ³
³ÄÄ³ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄú
³01³ Do not abuse multiple logins with two downloads at once.  ³ *
³02³ All uploaded dirs must be finished in 24h.                ³ 2x
³03³ We don't exist - no public talking.                       ³ BAN
³04³ No cheating, auto refresh (pFTP, RiSCFTP...)              ³ BAN
³ÄÄ³ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄú
³  ³ 0DAY (RiP) RULES                                          ³
³ÄÄ³ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄú
³05³ Upload 0day stuff only, nothing older than 24h of today.  ³ 2x
³06³ Only English/Norwegian stuff.                             ³ 2x
³07³ Upload in correct directory.                              ³ 2x
³08³ Only Win9x/NT releases.                                   ³ 3x
³09³ Beta/RC/Build ok.                                         ³ *
³10³ .ZIP files only, max filesize is 5mb need .diz/.nfo       ³ 2x
³11³ Only 8.3 filenames (12345678.zip)                         ³ 2x
³12³ Dirname must contain group tag and version number.        ³ 2x
³13³ Size limits: 10mb for util/game, bigger need approval!    ³ 3x
³14³ Not wanted: Kiddi/SS/US Tax/Freeware                      ³ 3x
³ÄÄ³ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄú
³  ³ MP3 RULES                                                 ³
³ÄÄ³ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄú
³15³ Only 0day and 2001 releases.                              ³ 3x
³16³ Only trance/pop/rap/hip-hop.                              ³ 3x
³17³ No releases bigger than 30mb. Unless approved.            ³ 3x
³ÄÄ³ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄú
³  ³ iSO RULES                                                 ³
³ÄÄ³ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄú
³18³ Only updates/cheats/docs allowed, unless approved.        ³ 3x
³19³ Only games, no applications, unless approved.             ³ 3x
³ÄÄ³ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄú
³  ³ VCD RULES                                                 ³
³ÄÄ³ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄú
³20³ No VCD uploads wanted, unless approved/requested.         ³ 5x
ÀÄÄ+ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ+ÄÄÄÄÄÄú


