.-=----------------------------------------------------[SITE LASTON]--=-.
| USAGE: SITE LASTON <user>                                             |
|-=-------------------------------------------------------------------=-|
| Send this command to the server if you want to know user last seen on |
| EXAMPLE: SITE LASTON red                                              |
| FLAGS  : *                                                            |
`-----------------------------------------------------------------------'