.-=-----------------------------------------------------[USER FLAGS]--=-.
| FLAG       DOES                                                       |
|-=-------------------------------------------------------------------=-|
| 1          User is siteop.                                            |
| 2          User is Groupadmin of his/her first public                 |
| 3          User cannot change group.                                  |
| 4          Allows to log in when site is full.                        |
| 5          --not used yet--                                           |
| 6          User is deleted.                                           |
| 7          User is cositeop.                                          |
| 8          User is annonymous.                                        |
| 9          --not used yet--                                           |
|-=-------------------------------------------------------------------=-|
| A          User is allowed to use site NUKE.                          |
| B          User is allowed to use site UNNUKE.                        |
| C          User is allowed to use site UNDUPE.                        |
| D          User is allowed to use site KICK.                          |
| E          User is allowed to use site KILL/SWHO.                     |
| F          User is allowed to use site TAKE.                          |
| G          User is allowed to use site GIVE.                          |
| H          This allows you to view users ( site USER/USERS )          |
| I          User is allowed to idle forever.                           |
| J          Custom flag 1                                              |
| K          Custom flag 2                                              |
| L          Custom flag 3                                              |
| M          Custom flag 4                                              |
| N          Custom flag 5                                              |
`-=-------------------------------------------------------------------=-'