.-=-------------------------------------------------[SITE ADDSITEOP]--=-.
| USAGE: SITE ADDSITEOP <user>                                          |
|-=-------------------------------------------------------------------=-|
| Send this command to the server if you want to mark a user as siteop. |
| EXAMPLE: SITE ADDSITEOP red                                           |
| FLAGS  : 1, 7                                                         |
`-----------------------------------------------------------------------'