.-=-----------------------------------------------------[SITE ADDIP]--=-.
| USAGE: SITE ADDIP <user> <ip>                                         |
|-=-------------------------------------------------------------------=-|
| Send this command to the server if you want to add an IP to the user  |
| EXAMPLE: SITE ADDIP red *@*                                           |
| FLAGS  : 1, 7                                                         |
`-----------------------------------------------------------------------'